server:
  port: 8190

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/joboffers

joboffers:
  http:
    client:
      config:
        connectionTimeout: 1000
        port: 5057
        readTimeout: 1000
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com:5057/offers